# Generated by Django 3.2.9 on 2022-03-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stellaris', '0003_partytrayscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(max_length=11)),
                ('email', models.EmailField(max_length=80)),
                ('pax', models.PositiveBigIntegerField(default=15)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('remarks', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartyTraysProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='images/foods')),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('availability', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellaris.partytrayscategory')),
            ],
            options={
                'verbose_name_plural': 'Party Trays Product',
            },
        ),
    ]
