# Generated by Django 3.2.9 on 2022-03-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellaris', '0004_partytraysproduct_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pax',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
