# Generated by Django 3.2.9 on 2022-03-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellaris', '0006_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
